[package]
name = "token-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
near-contract-standards = "4.1.0"
near-sdk = "4.1.0"
near-sdk-contract-tools = "0.7.0"
thiserror = "1.0.40"

[lib]
crate-type = ["cdylib"]
